# Generated by Django 5.2.1 on 2025-05-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deelnemers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voornaam", models.CharField(max_length=64)),
                ("achternaam", models.CharField(max_length=64)),
                ("ploegnaam", models.CharField(max_length=64)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
