# Generated by Django 5.2.1 on 2025-05-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deelnemers", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Deelnemers",
            new_name="Deelnemer",
        ),
    ]
