# Generated by Django 5.2.1 on 2025-05-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deelnemers", "0002_rename_deelnemers_deelnemer"),
    ]

    operations = [
        migrations.AddField(
            model_name="deelnemer",
            name="foto",
            field=models.ImageField(
                blank=True, null=True, upload_to="deelnemers_fotos/"
            ),
        ),
    ]
