# Generated by Django 5.2.1 on 2025-05-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deelnemers", "0004_deelnemer_clan_deelnemer_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deelnemer",
            name="email",
        ),
        migrations.RemoveField(
            model_name="deelnemer",
            name="foto",
        ),
        migrations.AddField(
            model_name="deelnemer",
            name="naamvoornaam",
            field=models.CharField(default="Voornaam Achternaam", max_length=128),
        ),
        migrations.AlterField(
            model_name="deelnemer",
            name="ploegnaam",
            field=models.CharField(default="Geen ploegnaam", max_length=64),
        ),
    ]
