# Generated by Django 5.2.1 on 2025-05-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Koers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naam", models.CharField(max_length=64)),
                ("niveau", models.CharField(max_length=64)),
                ("afkorting", models.CharField(max_length=64)),
                ("land", models.CharField(max_length=64)),
                ("koersvolgnummer", models.CharField(max_length=64)),
            ],
        ),
    ]
