# Generated by Django 5.2.1 on 2025-05-21 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("deelnemers", "0003_deelnemer_foto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Koers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naam", models.CharField(max_length=64)),
                ("uci_code", models.CharField(max_length=64)),
                ("land", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="KoersEditie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jaar", models.IntegerField()),
                ("status", models.CharField(max_length=64)),
                (
                    "derde_plaats",
                    models.ManyToManyField(
                        related_name="derde_plaats", to="deelnemers.deelnemer"
                    ),
                ),
                (
                    "eerste_plaats",
                    models.ManyToManyField(
                        related_name="eerste_plaats", to="deelnemers.deelnemer"
                    ),
                ),
                (
                    "koers",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edities",
                        to="koersen.koers",
                    ),
                ),
                (
                    "tweede_plaats",
                    models.ManyToManyField(
                        related_name="tweede_plaats", to="deelnemers.deelnemer"
                    ),
                ),
            ],
        ),
    ]
