# Generated by Django 5.2.1 on 2025-05-29 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("koersen", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="koers",
            options={"verbose_name": "Koers", "verbose_name_plural": "Koersen"},
        ),
    ]
