# Generated by Django 5.2.1 on 2025-06-01 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deelnemers", "0005_remove_deelnemer_email_remove_deelnemer_foto_and_more"),
        ("koersen", "0002_alter_koers_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="KoersEditie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("editie", models.CharField(max_length=64)),
                ("koersstatus", models.CharField(max_length=64)),
                ("uitslagstatus", models.CharField(max_length=64)),
                ("jaar", models.IntegerField()),
                (
                    "derde_plaats",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derde_plaats",
                        to="deelnemers.deelnemer",
                    ),
                ),
                (
                    "eerste_plaats",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eerste_plaats",
                        to="deelnemers.deelnemer",
                    ),
                ),
                (
                    "koers",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="koersen.koers"
                    ),
                ),
                (
                    "tweede_plaats",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tweede_plaats",
                        to="deelnemers.deelnemer",
                    ),
                ),
            ],
        ),
    ]
