# Generated by Django 5.2.1 on 2025-06-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deelnemers", "0005_remove_deelnemer_email_remove_deelnemer_foto_and_more"),
        ("koersen", "0003_koerseditie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="koerseditie",
            name="derde_plaats",
        ),
        migrations.RemoveField(
            model_name="koerseditie",
            name="eerste_plaats",
        ),
        migrations.RemoveField(
            model_name="koerseditie",
            name="tweede_plaats",
        ),
        migrations.AddField(
            model_name="koerseditie",
            name="derde_plaats",
            field=models.ManyToManyField(
                related_name="derde_plaats", to="deelnemers.deelnemer"
            ),
        ),
        migrations.AddField(
            model_name="koerseditie",
            name="eerste_plaats",
            field=models.ManyToManyField(
                related_name="eerste_plaats", to="deelnemers.deelnemer"
            ),
        ),
        migrations.AddField(
            model_name="koerseditie",
            name="tweede_plaats",
            field=models.ManyToManyField(
                related_name="tweede_plaats", to="deelnemers.deelnemer"
            ),
        ),
    ]
